# LariNetwork Bitcoin SV Configuration

# Network
regtest=1
dnsseed=0
upnp=0

# RPC
server=1
rpcuser=lariuser
rpcpassword=laripassword
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0

# Mining
gen=1

# Connections
connect=127.0.0.1:19444
listen=1
bind=0.0.0.0:19444

# Misc
txindex=1
