# LariNetwork Configuration
regtest=1
server=1
rpcuser=lariuser
rpcpassword=laripassword
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0
txindex=1
addressindex=1
timestampindex=1
spentindex=1
zmqpubrawtx=tcp://0.0.0.0:28332
zmqpubhashblock=tcp://0.0.0.0:28332
rpcworkqueue=100
rpcthreads=4
rest=1
# P2P Configuration
listen=1
bind=0.0.0.0:19444
