# JpyNetwork Configuration
regtest=1
server=1
rpcuser=jpyuser
rpcpassword=jpypassword
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0
txindex=1
addressindex=1
timestampindex=1
spentindex=1
zmqpubrawtx=tcp://0.0.0.0:28332
zmqpubhashblock=tcp://0.0.0.0:28332
rpcworkqueue=100
rpcthreads=4
rest=1
# P2P Configuration
listen=1
bind=0.0.0.0:18444
# Connect to existing nodes
addnode=3.27.37.63:18444
# Connect to new nodes
addnode=35.77.230.45:18444
addnode=18.179.29.65:18444
# Mandatory consensus parameters
excessiveblocksize=2000000000
maxstackmemoryusageconsensus=100000000
