version: '3'
services:
  node1:
    container_name: node1
    image: bitcoinsv/bitcoin-sv:1.0.8.beta
    volumes:
      - ./config/bitcoin.conf:/root/.bitcoin/bitcoin.conf
    ports:
      - '18332:18332'
      - '18333:18333'
      - '18444:18444'
    networks:
      - regtest_default
    restart: always

networks:
  regtest_default:
    driver: bridge
