# JpyNetwork Bitcoin SV Configuration

# Network
regtest=1
dnsseed=0
upnp=0

# RPC
server=1
rpcuser=bitcoin
rpcpassword=bitcoin
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0

# Mining
gen=1

# Connections
connect=3.107.165.86:18444
connect=3.26.38.112:18444
listen=1
bind=0.0.0.0:18444

# Misc
txindex=1
