version: '3'

services:
  jpynetwork-node:
    image: bitcoinsv/bitcoin-sv:1.0.8.beta
    container_name: jpynetwork-node
    volumes:
      - ./jpynetwork/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      - ./jpynetwork/data:/home/bitcoin/.bitcoin/data
    ports:
      - "18332:18332"
      - "18333:18333"
      - "18444:18444"
    command: bitcoind -excessiveblocksize=2000000000 -maxstackmemoryusageconsensus=100000000
    networks:
      - bsv-network

  larinetwork-node:
    image: bitcoinsv/bitcoin-sv:1.0.8.beta
    container_name: larinetwork-node
    volumes:
      - ./larinetwork/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      - ./larinetwork/data:/home/bitcoin/.bitcoin/data
    ports:
      - "19332:18332"
      - "19333:18333"
      - "19444:18444"
    command: bitcoind -excessiveblocksize=2000000000 -maxstackmemoryusageconsensus=100000000
    networks:
      - bsv-network

  token-bridge:
    build: ./token-bridge
    container_name: token-bridge
    ports:
      - "5001:5001"
    networks:
      - bsv-network
    depends_on:
      - jpynetwork-node
      - larinetwork-node

networks:
  bsv-network:
    driver: bridge
